<html>
<head>
<title>Неизвестная ошибка</title>
<style>
table.db_err {
  width: 100%;
  height: 50%;
}
td.db_err {
  vertical-align: bottom;
  text-align: center;
}
div.db_err {
  font-family: tahoma, arial, verdana, sans-serif, Lucida Sans;
  font-size: 16px;
  line-height: 160%;
  padding: 40px;
  color: #777;
}
</style>
</head>
<body>
<table class="db_err">
<tr><td class="db_err"><div class="db_err">К сожалению, сервер временно недоступен. Попробуйте повторить действие чуть позже.</div></td></tr>
</table>
<!-- generated by 633123 -->
</body></html>