try{stManager.done('lang0_0.js');}catch(e){}
audio_do_you_want_flash='Хотите перейти на страницу установки проигрывателя?';
audio_you_need_flash='Для того чтобы воспользоваться аудиосервисом, Вам необходимо установить Flash-проигрыватель.';
box_cancel='Отмена';
box_close='Закрыть';
box_loading='Загрузка...';
box_no='Нет';
box_restore='Восстановить';
box_save='Сохранить';
box_send='Отправить';
box_yes='Да';
captcha_cancel='Отмена';
captcha_enter_code='Введите код с картинки';
captcha_send='Отправить';
claims_flood_error='Вы уже отправили несколько жалоб. Пожалуйста, повторите попытку спустя некоторое время.';
datepicker_date_format='{day} {month} {year}';
datepicker_month_format='{month} {year}';
functions_sure_delete='Вы действительно хотите удалить эту запись?';
global_add='Добавить';
global_add_media_more='Другое..';
global_back='Назад';
global_Complain_video='Пожаловаться';
global_cancel='Отмена';
global_captcha_input_here='Введите код сюда';
global_changes_saved='Изменения сохранены';
global_charged_zone_continue='Продолжить';
global_charged_zone_title='Предупреждение';
global_close='Закрыть';
global_continue='Продолжить';
global_date=['','{day} {month} {year}','вчера','сегодня','завтра'];
global_day_label='День:';
global_delete='Удалить';
global_done='Готово';
global_dont_delete='Не удалять';
global_edit='Редактировать';
global_error='Ошибка';
global_error_occured='Произошла ошибка';
global_lang_box_title='Выбор языка';
global_last_notifitications='Последние уведомления';
global_media_selector_more='Ещё';
global_min='Свернуть';
global_mobile_need_validation='Для этого действия необходима привязка номера телефона. {link}Привязать номер »{/link}';
global_money_amount_rub=['','%s рубль','%s рубля','%s рублей'];
global_money_amount_rub_from=['','от %s рубля','от %s рублей','от %s рублей'];
global_money_amount_rub_text=['','рубль','рубля','рублей'];
global_money_amount_votes_text=['','голос','голоса','голосов'];
global_month_label='Месяц:';
global_notify_show_all='Показать все';
global_not_activated_title='Привязка номера телефона';
global_num_date_year_time=['','{num_day}.{month}.{short_year} {num_hour}:{minute}','вчера, {num_hour}:{minute}','сегодня, {num_hour}:{minute}','завтра, {num_hour}:{minute}'];
global_n_votes=['','%s голос','%s голоса','%s голосов'];
global_online=['','Online','Online'];
global_online_sm=['','online','online'];
global_privacy_except='кроме:';
global_rating_box_header='Рейтинг';
global_recommended_exceeded=['','Рекомендуемый объем превышен на %s знак.','Рекомендуемый объем превышен на %s знака.','Рекомендуемый объем превышен на %s знаков.'];
global_recommended_lines=['','Рекомендуемый объем превышен на %s строку.','Рекомендуемый объем превышен на %s строки.','Рекомендуемый объем превышен на %s строк.'];
global_reply_to='ответ {user}';
global_save='Сохранить';
global_search_not_found='По запросу {search} ничего не найдено.';
global_to_top='Наверх';
global_try_to_activate='Устали вводить коды? Пройдите бесплатную<br>{link}валидацию через мобильный телефон &#187;{/link}';
global_unknown_error='Неизвестная ошибка';
global_vkontakte='ВКонтакте';
global_warning='Предупреждениe';
global_write_msg='Написать сообщение';
global_X_people=['','%s человек','%s человека','%s человек'];
global_year_label='Год:';
graph_day_fullmon_year_hour='{day} {dayMonth} {year}, {hour}:00';
graph_day_fullmon_year_hour_min='{day} {dayMonth} {year}, {hour}:{min}';
guest_password='Пароль';
Higher_education='Высшее образование';
head_fr_online_tip='Показать друзей онлайн';
head_search_results='Результаты поиска';
Interests='Интересы:';
im_already_shown='Окно Мгновенных сообщений уже открыто в Вашем браузере, Вам достаточно просто перейти на него.';
im_already_shown_title='Мгновенные сообщения';
its_spam='Это спам';
its_spam_sm='Это спам';
leftAd_Details='Подробнее';
leftAd_details='подробнее';
leftAd_news='Новости';
leftAd_reminder='Напоминание';
left_delete_unpaid_gifts_text='Вы уверены, что хотите удалить все неоплаченные подарки?';
left_delete_unpaid_gifts_title='Удаление подарков';
Military_place='Войсковая часть:';
Month1='Январь';
Month10='Октябрь';
Month10_of='Октября';
Month11='Ноябрь';
Month11_of='Ноября';
Month12='Декабрь';
Month12_of='Декабря';
Month1_of='Января';
Month2='Февраль';
Month2_of='Февраля';
Month3='Март';
Month3_of='Марта';
Month4='Апрель';
Month4_of='Апреля';
Month5='Май';
Month5_of='Мая';
Month6='Июнь';
Month6_of='Июня';
Month7='Июль';
Month7_of='Июля';
Month8='Август';
Month8_of='Августа';
Month9='Сентябрь';
Month9_of='Сентября';
month10sm_of='окт';
month10_of='октября';
month11sm_of='ноя';
month11_of='ноября';
month12sm_of='дек';
month12_of='декабря';
month1sm_of='янв';
month1_of='января';
month2sm_of='фев';
month2_of='февраля';
month3sm_of='мар';
month3_of='марта';
month4sm_of='апр';
month4_of='апреля';
month5sm_of='мая';
month5_of='мая';
month6sm_of='июн';
month6_of='июня';
month7sm_of='июл';
month7_of='июля';
month8sm_of='авг';
month8_of='августа';
month9sm_of='сен';
month9_of='сентября';
pagination_allpages='Все';
privacy_custom_title='Настройки приватности';
privacy_N_friends_more=['','и ещё %s друга','и ещё %s друзей','и ещё %s друзей'];
privacy_N_friends_some=['','и ещё %s друг','и ещё %s друга','и ещё %s друзей'];
privacy_options_advanced_settings='Все, кроме..';
privacy_options_advanced_settings_dat='всем, кроме..';
privacy_options_all_users='Все пользователи';
privacy_options_all_users_dat='всем пользователям';
privacy_options_friends_and_friends_dat='друзьям и друзьям друзей';
privacy_options_friends_only='Только друзья';
privacy_options_friends_only_dat='только друзьям';
privacy_options_nobody='Никто';
privacy_options_only_me='Только я';
privacy_options_only_me_dat='только мне';
privacy_options_some_friends='Некоторые друзья';
privacy_options_some_friends_dat='некоторым друзьям';
privacy_options_some_friend_lists='Некоторые списки друзей';
privacy_options_some_friend_lists_dat='некоторым спискам друзей';
privacy_save='Сохранить';
Religion='Мировоззрение:';
Remove_from_friends='Убрать из друзей';
rate_you_have_N_unused=['','У Вас <b>%s</b> неиспользованный голос.','У Вас <b>%s</b> неиспользованных голоса.','У Вас <b>%s</b> неиспользованных голосов.'];
Save='Сохранить';
Secondary_education='Среднее и дополнительное образование';
Sex='Пол:';
Sex_fm='Женский';
Sex_m='Мужской';
search_by_app='по приложениям';
search_by_audio='по аудиозаписям';
search_by_event='по событиям';
search_by_goods='по товарам';
search_by_group='по группам';
search_by_note='по заметкам';
search_by_person='по людям';
search_by_question='по вопросам';
search_by_status='по новостям';
search_by_topic='по темам';
search_by_video='по видеозаписям';
select_chair_not_selected='Не выбрана';
select_chair_select='Введите название';
select_city_not_found='Город не найден';
select_city_not_selected='Не выбран';
select_city_other_city='Другой';
select_city_select='Введите название';
select_class_not_selected='Не выбран';
select_country_full_list='Полный список';
select_country_not_found='Страна не найдена';
select_country_not_selected='Не выбрана';
select_country_select='Введите страну';
select_district_not_selected='Не выбран';
select_eduform_not_selected='Не выбрана';
select_edustatus_not_selected='Не выбран';
select_fac_not_selected='Не выбран';
select_house_not_found='Дом не найден';
select_house_not_selected='Не выбран';
select_house_select='Введите номер';
select_place_not_found='Название не найдено';
select_place_not_selected='Не выбрано';
select_place_select='Введите название';
select_school_not_selected='Не выбрана';
select_school_select='Введите название';
select_station_not_selected='Не выбрана';
select_street_not_found='Улица не найдена';
select_street_not_selected='Не выбрана';
select_street_select='Введите название';
select_uni_not_selected='Не выбран';
select_uni_select='Введите название';
sex_fm='женский';
sex_m='мужской';
share_go='Перейти';
Today='Сегодня';
Town='Город:';
text_exceeds_symbol_limit=['','Допустимый объем превышен на %s знак.','Допустимый объем превышен на %s знака.','Допустимый объем превышен на %s знаков.'];
text_N_symbols_remain=['','Остался %s знак.','Осталось %s знака.','Осталось %s знаков.'];
today='сегодня';
top_search='Искать {query}';
top_search_news='Искать {query} в новостях';
Updates='Обновления';
updates='обновления';
videofile_num=['','видеозапись','видеозаписи','видеозаписей'];
votes_flex=['','голос','голоса','голосов'];
Work_place='Место работы:';
yesterday='вчера';
// section = 0; version = 424;

friends_no_user_selected='Вы не выбрали ни одного пользователя.';
// section = 2; version = 207;

audio_add_to_audio='Добавить в Мои Аудиозаписи';
audio_add_to_group='Добавить в аудиозаписи сообщества';
audio_album_no_recs='В альбоме ещё нет аудиозаписей.';
audio_change_album_name='Изменить название';
audio_claim_delete='удалить аудиозапись';
audio_claim_objection='заполнив специальную форму';
audio_claim_warning='Аудиозапись {audio} была изъята из публичного доступа в связи с обращением правообладателя.';
audio_claim_warning_objection='Аудиозапись {audio} была изъята из публичного доступа в связи с обращением правообладателя.<br><br>Вы можете оспорить жалобу, {objection_link}, или {delete_link}, нарушающую авторские права.';
audio_claim_warning_text='Аудиозапись {audio} была изъята из публичного доступа в связи с обращением правообладателя.<br><br>Вы можете {delete_link}, нарушающую авторские права.';
audio_claim_warning_title='Спорная аудиозапись';
audio_common_list='общий список';
audio_crap_warning='Аудиозапись {audio} была изъята из публичного доступа по причине отсутствия культурной ценности.';
audio_crap_warning_text='Аудиозапись {audio} была изъята из публичного доступа по причине отсутствия культурной ценности.<br><br>Вы можете {delete_link}.';
audio_crap_warning_title='Спорная аудиозапись';
audio_current_playing_from='Сейчас играет — {playlist}';
audio_delete='удалить';
audio_delete_album='Удалить альбом';
audio_delete_album_are_you_sure='Вы уверены, что хотите удалить этот альбом?';
audio_delete_album_button='Удалить';
audio_delete_album_title='Удаление альбома';
audio_delete_all_title='Удаление аудиозаписей';
audio_edit_additionally='Дополнительно';
audio_edit_album='Редактировать альбом';
audio_edit_album_title='Редактирование альбома';
audio_edit_cancel='Отмена';
audio_edit_deleting='Удаление аудиозаписи';
audio_edit_deleting_error='При удалении файла произошла ошибка:';
audio_edit_dont_show_search='Не выводить при поиске';
audio_edit_edit='Сохранить';
audio_edit_editing='Редактирование аудиозаписи';
audio_edit_name='Название:';
audio_edit_no='Нет';
audio_edit_noname='Без названия';
audio_edit_singer='Исполнитель:';
audio_edit_sure_delete='Вы действительно хотите удалить эту аудиозапись?';
audio_edit_text='Слова песни:';
audio_edit_unknown='Неизвестный исполнитель';
audio_edit_yes='Да';
audio_enter_album_name='Введите название альбома';
audio_error_loading='При загрузке аудиозаписи произошла ошибка. Попробуйте обновить страницу.';
audio_export_tip='Транслировать на мою страницу';
audio_friends_feed='Обновления друзей';
audio_global_search_found=['','В поиске найдена %s аудиозапись','В поиске найдено %s аудиозаписи','В поиске найдено %s аудиозаписей'];
audio_group_no_recs='В сообществе ещё нет аудиозаписей.';
audio_header='Мои Аудиозаписи';
audio_loading_error='Возникла ошибка, код ошибки: {code}';
audio_lyrics_not_found='Текст песни не найден';
audio_need_flash_title='Необходим Flash-проигрыватель';
audio_new_album_title='Новый альбом';
audio_not_found='Аудиозапись не найдена';
audio_no_audios_found='По запросу {query} не найдено ни одной аудиозаписи';
audio_no_rec_load_msg='Здесь Вы можете хранить Ваши аудиозаписи.<br>Для того, чтобы загрузить Вашу первую аудиозапись, {link}нажмите здесь{/link}.';
audio_no_your_recs='У Вас ещё нет аудиозаписей';
audio_only_foreign_music='только зарубежные';
audio_popular_audios='Популярные аудиозаписи';
audio_recommended_audios='Рекомендуемые аудиозаписи';
audio_repeat_tooltip='Повторять эту композицию';
audio_search_enter_audio_name='Введите название или исполнителя';
audio_search_not_found='По запросу {search} ничего не найдено.';
audio_search_results='Результаты поиска';
audio_show_more_audios='Показать больше аудиозаписей';
audio_show_recommendations='Показать похожие';
audio_shuffle='Перемешать';
audio_success_msg_multiple='Все аудиозаписи успешно загружены.';
audio_title_search='Поиск по запросу {q}';
audio_uploading_over='Загрузка завершена';
audio_upl_not_enabled_ingroup='В данной группе отключены аудиозаписи, поэтому загрузка аудиофайлов недоступна.';
audio_user_no_recs='У пользователя ещё нет аудиозаписей.';
// section = 3; version = 106;

apps_addapp='Добавить приложение';
apps_addedtogroup='Приложение добавлено в группу';
apps_app_settings='Настройки приложения';
apps_balance_minus_X_done=['','Вы уменьшили баланс приложения на <b>%s</b> голос.','Вы уменьшили баланс приложения на <b>%s</b> голоса.','Вы уменьшили баланс приложения на <b>%s</b> голосов.'];
apps_balance_plus_X_done=['','Вы пополнили баланс приложения на <b>%s</b> голос.','Вы пополнили баланс приложения на <b>%s</b> голоса.','Вы пополнили баланс приложения на <b>%s</b> голосов.'];
apps_cancel='Отмена';
apps_change_settings='Настроить';
apps_delete_admin_title='Удаление администратора';
apps_done='Готово';
apps_dont_show='Больше не показывать';
apps_edit='редактировать';
apps_editapp='Редактировать';
apps_games_of_group='Игры группы';
apps_game_added_to_group='Игра добавлена в группу';
apps_game_balance_minus_X_done=['','Вы уменьшили баланс игры на <b>%s</b> голос.','Вы уменьшили баланс игры на <b>%s</b> голоса.','Вы уменьшили баланс игры на <b>%s</b> голосов.'];
apps_game_balance_plus_X_done=['','Вы пополнили баланс игры на <b>%s</b> голос.','Вы пополнили баланс игры на <b>%s</b> голоса.','Вы пополнили баланс игры на <b>%s</b> голосов.'];
apps_game_need_X_votes=['','Игра просит Вас внести <b>%s</b> голос.','Игра просит Вас внести <b>%s</b> голоса.','Игра просит Вас внести <b>%s</b> голосов.'];
apps_global_game_search_found=['','В поиске найдена %s игра','В поиске найдено %s игры','В поиске найдено %s игр'];
apps_global_search_found=['','В поиске найдено %s приложение','В поиске найдено %s приложения','В поиске найдено %s приложений'];
apps_last_notifications='Последние оповещения';
apps_merchant_payment_title='Оплата покупки';
apps_my_apps='Мои приложения';
apps_my_games='Мои игры';
apps_need_X_votes=['','Приложение просит Вас внести <b>%s</b> голос.','Приложение просит Вас внести <b>%s</b> голоса.','Приложение просит Вас внести <b>%s</b> голосов.'];
apps_noappsingroup2='В группе не подключено ни одного приложения.';
apps_no_apps_found='По запросу {query} не найдено ни одного приложения.';
apps_no_games_found='По запросу {query} не найдено ни одной игры.';
apps_no_games_in_group='В группе не подключено ни одной игры.';
apps_no_notifications='Нет оповещений';
apps_of_group='Приложения группы';
apps_remove='Убрать';
apps_search_in_apps='Поиск по приложениям';
apps_show_more_apps='Показать больше приложений';
apps_show_more_games='Показать больше игр';
apps_X_apps_found=['','Найдено %s приложение','Найдено %s приложения','Найдено %s приложений'];
apps_X_games_found=['','Найдена %s игра','Найдены %s игры','Найдено %s игр'];
apps_youaddednoapps='Вы ещё не подключили ни одного приложения.';
apps_you_added_no_games='Вы ещё не подключили ни одной игры.';
apps_you_have_no_notifies='У Вас нет ни одного оповещения';
app_comments_hidecomms='Скрыть комментарии';
app_comments_showcomms='Показать комментарии';
// section = 4; version = 446;

video_add_to_public='Вернуть в публичный доступ';
video_comment_placeholder='Комментировать..';
video_delete_all_user_uploaded='Удалить все видеозаписи, загруженные пользователем?';
video_delete_from_public='Изъять из доступа';
video_delete_tag='Удалить отметку';
video_flash_needed='Для просмотра необходим {flash_player} последней версии.';
// section = 5; version = 152;

notes_cancel='Отмена';
notes_done='Готово';
notes_livejournal_delete='Удалить эту запись из <b>LiveJournal</b>.';
// section = 7; version = 64;

admin_added_items_digit_search='поиск цифр';
// section = 8; version = 2;

blank_note_not_found='Заметка не найдена';
// section = 10; version = 19;

events_ajax_inv_declined_spam='Приглашение отклонено и помечено как спам.';
events_fri='Пт';
events_goto_search='Перейти к поиску';
events_mon='Пн';
events_sat='Сб';
events_sun='Вс';
events_thu='Чт';
events_tue='Вт';
events_wed='Ср';
// section = 13; version = 76;

fave_return_to_fave='Закладки';
// section = 14; version = 82;

gifts_cansend_X_gifts=['','Вы можете отправить<br>не более <b>%s</b> подарка.','Вы можете отправить<br>не более <b>%s</b> подарков.','Вы можете отправить<br>не более <b>%s</b> подарков.'];
gifts_confirm_N_Votes=['','<b>%s</b> голос','<b>%s</b> голоса','<b>%s</b> голосов'];
gifts_confirm_send_to_N_friends=['','Подарок будет отправлен %s другу ({votes}). Продолжить?','Подарок будет отправлен %s друзьям ({votes}). Продолжить?','Подарок будет отправлен %s друзьям ({votes}). Продолжить?'];
gifts_free_send_left=['','Вы выбрали бесплатный подарок и можете отправить его <b>%s другу</b>.','Вы выбрали бесплатный подарок и можете отправить его <b>%s друзьям</b>.','Вы выбрали бесплатный подарок и можете отправить его <b>%s друзьям</b>.'];
gifts_rate_increase='При отправке этого подарка рейтинг получателя увеличится на <b>{gifts_count}</b>.';
gifts_X_gifts=['','<b>%s</b> подарок','<b>%s</b> подарка','<b>%s</b> подарков'];
gifts_X_votes=['','%s голос','%s голоса','%s голосов'];
// section = 15; version = 35;

groups_admins='Администраторы';
groups_admins_of_group='Администраторы группы';
groups_adspost_notify_pm='Личные сообщения';
groups_appl_rejected='Заявка отклонена.';
groups_assign='Назначить';
groups_assigned='Участник назначен руководителем.';
groups_assigning_manager='Назначение руководителя';
groups_cancel='отмена';
groups_cancel2='Отменить';
groups_create_enter='Пожалуйста, введите название группы';
groups_create_new='Создание нового сообщества';
groups_delete_manager='Удаление руководителя';
groups_deleting_link='Удаление ссылки';
groups_edit='Редактировать';
groups_editing_link='Редактирование ссылки';
groups_enter_name='Название';
groups_enter_post='Введите должность:';
groups_group_admin='Администратор группы';
groups_group_create_button='Создать сообщество';
groups_inv_cancelled='Приглашение отменено.';
groups_limit_message='К сожалению, Вы не можете быть подписаны более, чем на 5000 сообществ одновременно.';
groups_limit_title='Достигнут предел';
groups_no='Нет';
groups_officers='Руководители';
groups_officers_of_group='Руководители группы';
groups_partic_accepted='Участник принят.';
groups_partic_deleted='Участник удалён.';
groups_reject_invint='Отклонить приглашение';
groups_sure_delete_link='Вы действительно хотите удалить ссылку на эту группу?';
groups_sure_delete_manager='Вы действительно хотите удалить этого человека из руководителей?';
groups_to_all_posts='ко всем записям';
groups_unbanned='Пользователь удалён из бан-листа';
groups_yes='Да';
// section = 17; version = 175;

help_ccform_legal_need_email='Вы должны выразить согласие с тем, что указанный Вами адрес электронной почты может использоваться Администрацией Сайта для дальнейших коммуникаций по заявлению.';
help_ccform_legal_need_inform='Вы должны выразить своё согласие на обработку Администрацией Сайта Ваших персональных данных, указанных в заявлении, а также на то, что сведения, указанные в заявлении (включая персональные данные) и само заявление будут направлены Администрацией Сайта лицу, указанному Вами в качестве пользователя, разместившего спорный контент, а также могут быть направлены лицу, оспаривающему заявление.';
help_ccform_legal_need_is_owner='Вы должны подтвердить, что являетесь уполномоченным представителем правообладателя указанного спорного контента.';
help_ccform_legal_need_perjury='Вы должны подтвердить, что осознаете юридические последствия, которые может повлечь ложное обвинение в нарушении авторских прав.';
help_ccform_legal_need_unauthorized='Вы должны подтвердить, что спорный контент используется без согласия правообладателя.';
help_ccform_natural_need_email='Вы должны выразить согласие с тем, что указанный Вами адрес электронной почты может использоваться Администрацией Сайта для дальнейших коммуникаций по заявлению.';
help_ccform_natural_need_inform='Вы должны выразить своё согласие на обработку Администрацией Сайта Ваших персональных данных, указанных в заявлении, а также на то, что сведения, указанные в заявлении (включая персональные данные) и само заявление будут направлены Администрацией Сайта лицу, указанному Вами в качестве пользователя, разместившего спорный контент, а также могут быть направлены лицу, оспаривающему заявление.';
help_ccform_natural_need_owner='Вы должны подтвердить, что являетесь правообладателем указанного спорного контента.';
help_ccform_natural_need_perjury='Вы должны подтвердить, что осознаете юридические последствия, которые может повлечь ложное обвинение в нарушении авторских прав.';
help_ccform_natural_need_unauthorized='Вы должны подтвердить, что спорный контент используется без Вашего разрешения.';
help_ccform_need_rules='Вы должны согласиться с условиями правил рассмотрения заявлений, связанных с размещением контента на сайте ВКонтакте.';
help_ccobjection_need_email='Вы должны выразить согласие с тем, что указанный Вами адрес электронной почты может использоваться Администрацией Сайта для дальнейших коммуникаций по заявлению.';
help_ccobjection_need_inform='Вы должны выразить своё согласие с тем, что указанные выше данные о Вас и Ваше возражение будут направлены правообладателю.';
help_ccobjection_need_rules='Вы должны согласиться с условиями правил рассмотрения заявлений, связанных с размещением контента на сайте ВКонтакте.';
// section = 18; version = 123;

login_enter='Войти';
login_wrong_email_pwd='Указан неверный логин или пароль.';
// section = 21; version = 98;

mail_added_link='Ссылка';
mail_cancel='Отмена';
mail_close='Закрыть';
mail_delete='Удалить';
mail_deleteall1='Удалить все сообщения';
mail_delete_all_spam='Удалить все сообщения, содержащие спам?';
mail_error='Ошибка';
mail_im_get_invitation_link='Ссылка на беседу';
mail_im_joined_chat_from_invitation=['','{from} присоединился к беседе','{from} присоединилась к беседе'];
mail_marked_as_spam='Сообщение помечено как спам и удалено.';
// section = 22; version = 242;

matches_close='закрыть';
matches_closed='закрыто';
matches_no_accepted='Отказ принят.';
matches_open='открыть';
matches_user_deleted='Пользователь удалён из списка.';
matches_yes_accepted='Согласие принято.';
// section = 24; version = 1;

payments_amount_rubles=['','рубль','рубля','рублей'];
payments_amount_votes=['','голос','голоса','голосов'];
payments_cancel='Отмена';
payments_card_verified_msg='Вы подтвердили, что являетесь владельцем карты.';
payments_close='Закрыть';
payments_error='Ошибка';
payments_fee_full='Комиссия {amount} р. ({percent}%)';
payments_fee_votes=['','Сумма: %s рубль','Сумма: %s рубля','Сумма: %s рублей'];
payments_min_amount_limit_rubles='Минимальная сумма: %s рублей';
payments_msg_deleted='Сообщение удалено.';
payments_N_tries_left_msg=['','У Вас осталась одна попытка.','У Вас осталось %s попытки.','У Вас осталось %s попыток.'];
payments_payment_system_submit='Оплатить';
payments_please_enter_money='Пожалуйста, введите сумму платежа.';
payments_really_start_over_msg='Вы действительно хотите начать процедуру заново?';
payments_really_use_other_msg='Вы действительно хотите использовать другую карту для проведения платежей?';
payments_send='Отправить';
payments_thanks_for_comm='Спасибо за Ваш отзыв.';
payments_verify_start_over_header='Вы уверены?';
payments_verify_sum_currency='Валюта авторизационной транзакции:';
payments_verify_sum_dialog='Введите сумму авторизационной транзакции:';
payments_verify_sum_header='Введите сумму';
payments_verify_sum_howto_dialog='Сумму авторизационной транзакции Вы можете узнать:<br><ul class="listing"><li><span> обратившись в службу клиентской поддержки банка по телефону, указанному на обратной стороне Вашей карты. Сообщите оператору, что Вы только что произвели оплату в интернет-магазине, и, для подтверждения права на использование карты, Вам необходима информация о сумме транзакции. Вас попросят идентифицировать себя, после чего предоставят информацию.</span></li><li><span> через систему удаленного банковского обслуживания интернет-банк/банк-клиент – в случае предоставления данной услуги банком-эмитентом;</span></li><li><span> c помощью услуги SMS-информирования – в случае предоставления данной услуги банком-эмитентом.</span></li></ul>';
payments_verify_sum_howto_header='Как узнать сумму авторизационной транзакции';
payments_wait_verifying_msg='Пожалуйста, подождите. Проверка может занять 5-10 минут.';
payments_wrong_sum_msg='Сумма авторизационной транзакции введена неверно, попробуйте снова.';
payments_your_comm='Ваш отзыв';
payment_no_more_tries_msg='Сумма авторизационной транзакции введена неверно. Вы исчерпали количество попыток для этой авторизационной транзакции. Вам необходимо запустить процесс подтверждения заново, нажав кнопку &quot;Авторизовать карту&quot;.';
// section = 28; version = 233;

photos_cancel='Отмена';
photos_done='Готово';
photos_stop_uploading='Прервать загрузку';
photos_uploading_warning='Загрузка фотографий ещё продолжается. Вы уверены, что хотите покинуть страницу и прервать загрузку?';
photos_viewer_exit='Выйти из режима просмотра';
photo_comment_marked_as_spam='Комментарий помечен как спам.';
photo_dont_close='Пожалуйста, не закрывайте это окно, пока фотографии не загрузятся.';
photo_rotating='Поворачиваем';
photo_uploading_photo='Идёт загрузка фотографий';
// section = 30; version = 153;

ads_image_too_small='Вы пытаетесь загрузить слишком маленькую фотографию.<br>Выберите фотографию большего размера и повторите попытку.';
profile_custom_snippet_photo_error_size='{sorry}.<br>Фотография должна иметь размер не меньше {width} точек в ширину и  {height} точек в высоту.<br>Кроме того, нельзя использовать фотографии, у которых одна из сторон в несколько раз превышает другую.';
profile_enter_post='Написать сообщение..';
profile_mention_not_found='Страница не найдена';
profile_mention_start_typing='Начните вводить имя друга или название сообщества';
profile_oph_crop_desc='Осталось выбрать квадратную область для маленьких фотографий.<br>Выбранная миниатюра будет использоваться в новостях, личных сообщениях и комментариях.';
// section = 31; version = 316;

reg_sex_not_set='Не задан';
// section = 35; version = 99;

search_nothing_found='Ничего не найдено';
// section = 36; version = 151;

stats_data_empty='Нет данных';
stats_day_mon='{day} {month}';
stats_day_month_year='{day} {month} {year}';
stats_error_loading='Ошибка при загрузке';
stats_good_browser_box_msg='К сожалению, Ваш браузер не поддерживает отображение графиков статистики.<br><br>Чтобы использовать все возможности сайта, Вы можете загрузить и установить один из современных браузеров:';
stats_loading='Загрузка...';
stats_no_data='Отсутствуют входные данные';
// section = 38; version = 46;

paysupp_error='Ошибка';
// section = 39; version = 232;

wall_post_not_found='Запись не найдена';
wall_publish_now='Опубликовать сейчас';
wall_reply_to_post='Комментировать..';
wall_reply_to_post_link='Комментировать';
wall_send='Отправить';
// section = 41; version = 107;

vkontakte_ru='ВКонтакте';
// section = 42; version = 218;

fans_block_fan='Заблокировать';
fans_no_fans='На этого пользователя ещё никто не подписан.';
fans_no_idols='Этот пользователь ещё не подписан ни на одну страницу.';
fans_show_all_fans='Показать всех подписчиков';
fans_show_all_idols='Показать все интересные страницы';
// section = 54; version = 14;

abuse_goto_support='Если Вы хотите удалить страницу, созданную от Вашего имени, или свою старую страницу — пожалуйста, обратитесь <a class="wikiVkLink" href="http://vk.com/support?act=new&amp;from=abuse">в поддержку</a>. ';
// section = 58; version = 14;

offers_reban='Вернуть в список';
offers_unban='Удалить из списка';
// section = 59; version = 127;

mobile_act_not_activated_header='Привязка номера телефона';
mobile_apps_catalog_app_members=['','%s участник','%s участника','%s участников'];
mobile_edit_country_null='Не выбрана';
mobile_mail_im_joined_chat_from_invitation=['','{from} присоединился к беседе','{from} присоединилась к беседе'];
mobile_photos_albums_edit_album_btn='Сохранить';
mobile_photos_edit_save_btn='Сохранить';
mobile_profile_work_label='Место работы:';
mobile_wall_publish_postponed='Опубликовать сейчас';
mobile_zphoto_save_btn='Сохранить';
// section = 61; version = 36;

adslight_age_restriction_none='Не указывать';
// section = 67; version = 2;

print_close_text='Ваши наклейки в данный момент создаются. Вы уверены, что хотите закрыть страницу?';
print_close_title='Закрыть страницу';
print_epsp_hint='Векторный формат, предназначенный для печатного оборудования.<br>{tag}В файле добавлены вылеты и кривые, по которым наклейка будет вырезаться{/tag}';
print_eps_hint='Векторный формат изображения';
print_flood_error='Действие выполняется слишком часто, пожалуйста, попробуйте повторить попытку позже.';
print_group_change_address='Вы можете изменить адрес сообщества в {link}настройках{/link}.';
print_group_not_found='Сообщество не найдено';
print_group_no_address='Сообщество %s не имеет короткого адреса. Наклейки можно создать только для сообществ, у которых есть короткий адрес вида <b>vk.com/cafe</b>.';
print_group_placeholder='Введите название сообщества или адрес страницы';
print_png_hint='Растровый формат изображения';
print_stickers_example='Примеры наклеек';
print_user_change_address='Вы можете изменить адрес своей страницы в {link}настройках{/link}. ';
print_user_no_address='%s не имеет короткого адреса. Наклейки можно создать только для страниц, у которых есть короткий адрес вида <b>vk.com/cafe</b>.';
// section = 69; version = 20;

chronicle_landing_title='Новое фотоприложение';
// section = 70; version = 1;


var langConfig = {"id":0,"numDel":"<span class=\"num_delim\"> <\/span>","numDelS":" ","numDec":",","prepTags":["{prep_with}","{prep_With}","{prep_about}","{prep_About}","{prep_into}","{prep_Into}"],"prep":[["{prep_with},{prep_With}","С*,З*,Льв*","со,Со"],["{prep_with},{prep_With}","*,Са*,Се*,Сё*,Си*,Со*,Су*,Сэ*,Сю*,Ся*,За*,Зе*,Зё*,Зи*,Зо*,Зу*,Зэ*,Зю*,Зя*","с,С"],["{prep_about},{prep_About}","А*,О*,У*,И*,Э*","об,Об"],["{prep_about},{prep_About}","*","о,О"],["{prep_into},{prep_Into}","В*,Ф*,Льв*","во,Во"],["{prep_into},{prep_Into}","*,Ва*,Ве*,Вё*,Ви*,Во*,Ву*,Вэ*,Вю*,Вя*,Фа*,Фе*,Фё*,Фи*,Фо*,Фу*,Фэ*,Фю*,Фя*","в,В"]],"parent":0,"timeSys":["24hour"],"yearOffset":0,"flexLast":false,"revOrder":false,"RTL":false,"numRules":{"int":[[100,[11,12,13,14],3],[10,[1],1],[10,[2,3,4],2],["*",0,3]],"float":2},"sexRules":[[1,2],["*",1]],"larr":"&larr;","rarr":"&rarr;"};
var market_currency_count = ['RUB','UAH','KZT','USD','EUR'];

var qArr = [[0, getLang('search_by_person'), '', 'people', 0],
[1, getLang('search_by_group'), '', 'groups', 0x00800000],
[2, getLang('search_by_event'), '', 'events', 0x01000000],
[3, getLang('search_by_audio'), '', 'audio',  0x00000002],
[4, getLang('search_by_video'), '', 'video',  0x00400000],
[5, getLang('search_by_ad'), '', 'ads', 0x00000100],
[6, getLang('search_by_app'), '', 'apps', 0x00000020],
[7, getLang('search_by_question'), '', 'questions', 0x00000040],
[8, getLang('search_by_note'), '', 'notes', 0x02000000],
[9, getLang('search_by_topic'), '', 'topics', 0x00800000],
[11, getLang('search_by_status'), '', 'statuses', 0]];

var year_offset = langConfig.yearOffset;
var larr = langConfig.larr;
var rarr = langConfig.rarr;